server:
  contextPath: /sentinel-auth-server
  port: 8081

oauthdb:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2db
    user: oauth2user
    pass: password

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  accessTokenValidityInSeconds: 36000
  refreshTokenValidityInSeconds: 360000

custom:
  jarsDirectory: ~/myTemp