server:
  contextPath: /sentinel-oauth2-server
  port: 8081

oauthdb:
  jdbc:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2db
    user: oauth2user
    pass: password

logging:
  level:
    org.springframework.security: DEBUG

jwt:
  # The number of seconds the JWT will expire in
  expirationInSecs: 360000